version: '3.8'
services:
  frontend:
    image: 'hashicorpdemoapp/frontend:v1.0.9'
    environment:
      - NEXT_PUBLIC_PUBLIC_API_URL=

  nginx:
    image: nginx:alpine
    links:
      - 'public-api:public-api'
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  public-api:
    image: 'hashicorpdemoapp/public-api:v0.0.7'
    environment:
      - PRODUCT_API_URI=http://product-api:9090
      - PAYMENT_API_URI=http://payments:8080
    links:
      - 'product-api:product-api'
      - 'payments:payments'
    ports:
      - '8080:8080'

  product-api:
    image: 'hashicorpdemoapp/product-api:v0.0.22'
    volumes:
      - type: bind
        source: ./product-api-config/conf-from-vault.json
        target: /conf.json
    links:
      - 'product-db:product-db'
    ports:
      - '9090:9090'

  product-db:
    image: 'hashicorpdemoapp/product-api-db:v0.0.20'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=products
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

  payments:
    image: 'hashicorpdemoapp/payments:latest'

  vault-agent:
    image: 'vault:1.13.3'
    entrypoint: ["vault", "agent", "-config=/agent-config.hcl", "-config=/agent-template.hcl"]
    volumes:
      - type: bind
        source: ./vault-agent/agent-config.hcl
        target: /agent-config.hcl
      - type: bind
        source: ./vault-agent/config.json.tmpl
        target: /config.json.tmpl
      - type: bind
        source: ./vault-agent/agent-template.hcl
        target: /agent-template.hcl
      - type: bind
        source: ./product-api-config
        target: /product-api-config
      - type: bind
        source: ~/.vault-token
        target: /.vault-token
    environment:
      - VAULT_ADDR=http://host.docker.internal:8200