apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-db
  labels:
    app: product-api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api-db
  template:
    metadata:
      labels:
        app: product-api-db
    spec:
      containers:
      - name: product-api-db
        image: hashicorpdemoapp/product-api-db:v0.0.20
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: products
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_USER
            value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: product-api-db-service
spec:
  selector:
    app: product-api-db
  type: NodePort
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30000