apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api
  labels:
    app: public-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-api
  template:
    metadata:
      labels:
        app: public-api
    spec:
      containers:
      - name: product-api
        image: hashicorpdemoapp/public-api:v0.0.7
        ports:
          - containerPort: 9090
        env:
          - name: PRODUCT_API_URI
            value: http://product-api-service:9090
          - name: PAYMENT_API_URI
            value: http://payments:8080
---
apiVersion: v1
kind: Service
metadata:
  name: public-api-service
spec:
  selector:
    app: public-api
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002